[global]
font = JetbrainsMono 10
foreground = "#%% foreground %%"
background = "#%% background aplha=0.8 %%"

height = (16, 256)
width = (16, 512)
offset = (12, 12)

min_icon_size = 64
max_icon_size = 64
corner_radius = 8
frame_width = 0
gap_size = 2

[urgency_low]
timeout = 4

[urgency_normal]
timeout = 8

[urgency_critical]
timeout = 16
