$wallpaper  = {{ image }}
$background = rgb({{ colors.background.default.hex_stripped }})
$foreground = rgb({{ colors.on_background.default.hex_stripped }})
$color0     = rgb({{ base16.base00.default.hex_stripped }})
$color1     = rgb({{ base16.base01.default.hex_stripped }})
$color2     = rgb({{ base16.base02.default.hex_stripped }})
$color3     = rgb({{ base16.base03.default.hex_stripped }})
$color4     = rgb({{ base16.base04.default.hex_stripped }})
$color5     = rgb({{ base16.base05.default.hex_stripped }})
$color6     = rgb({{ base16.base06.default.hex_stripped }})
$color7     = rgb({{ base16.base07.default.hex_stripped }})
$color8     = rgb({{ base16.base08.default.hex_stripped }})
$color9     = rgb({{ base16.base09.default.hex_stripped }})
$color10    = rgb({{ base16.base0a.default.hex_stripped }})
$color11    = rgb({{ base16.base0b.default.hex_stripped }})
$color12    = rgb({{ base16.base0c.default.hex_stripped }})
$color13    = rgb({{ base16.base0d.default.hex_stripped }})
$color14    = rgb({{ base16.base0e.default.hex_stripped }})
$color15    = rgb({{ base16.base0f.default.hex_stripped }})
