[urgency_low]
background = "{{ colors.background.default.hex }}",
foreground = "{{ colors.on_background.default.hex }}",
frame_color = "{{ colors.on_background.default.hex }}"

[urgency_normal]
background = "{{ colors.background.default.hex }}",
foreground = "{{ base16.base03.default.hex }}"
frame_color = "{{ base16.base03.default.hex }}"

[urgency_critical]
background = "{{ colors.background.default.hex }}",
foreground = "{{ base16.base01.default.hex }}"
frame_color = "{{ base16.base01.default.hex }}"
