[urgency_low]
background = "{{ colors.background.default.hex }}"
foreground = "{{ colors.on_background.default.hex }}"
frame_color = "{{ colors.on_background.default.hex }}"

[urgency_normal]
background = "{{ colors.background.default.hex }}"
foreground = "#f4bf75"
frame_color = "#f4bf75"

[urgency_critical]
background = "{{ colors.background.default.hex }}"
foreground = "#ac4142"
frame_color = "#ac4142"
