$wallpaper  = ~/.cache/moomin/walls/light-moomin-fishing.png
$background = rgb(fafaee)
$foreground = rgb(1a1c15)
$color0     = rgb(fcfcfd)
$color1     = rgb(e1e3e1)
$color2     = rgb(c5c9c5)
$color3     = rgb(aab0a9)
$color4     = rgb(8e978d)
$color5     = rgb(727d71)
$color6     = rgb(576454)
$color7     = rgb(3b4a38)
$color8     = rgb(3b4a38)
$color9     = rgb(d0cfd6)
$color10    = rgb(dedbe1)
$color11    = rgb(ecebf0)
$color12    = rgb(e5e5ea)
$color13    = rgb(eeedf1)
$color14    = rgb(eae9ed)
$color15    = rgb(f0eff3)
