#!/usr/bin/env bash

ROFI_CFG=~/.config/rofi/power.rasi

SHUTDOWN="mode_off_on"
RESTART="refresh"
SLEEP="dark_mode"
LOCK="lock"

PICK=$(
    printf "$LOCK\n$SLEEP\n$RESTART\n$SHUTDOWN" | \
    rofi -dmenu -config $ROFI_CFG
)

case "$PICK" in
    "$LOCK") hyprlock ;;
    "$RESTART") reboot ;;
    "$SHUTDOWN") poweroff ;;
    "$SLEEP") systemctl suspend ;;
    *) exit 0 ;;
esac
