#!/usr/bin/env bash

CONFIG=~/.config
CACHE=~/.cache

WALLS=~/Pictures/walls
THUMBNAILS=$CACHE/thumbnails/walls
ROFI_CFG=$CONFIG/rofi/walls.rasi

mkdir -p $WALLS
mkdir -p $CACHE

for WALL in $WALLS/*; do
    BASENAME=$(basename $WALL)
    THUMBNAIL=$THUMBNAILS/$BASENAME
    if [ ! -f $THUMBNAIL ]; then
        magick convert \
            -strip $WALL \
            -thumbnail x540^ \
            -gravity center \
            -extent 330x500 \
            $THUMBNAIL
    fi
done

WALLPAPER=$(
    for WALL in $WALLS/*; do
        printf "$WALL\0icon\x1f$THUMBNAILS/$(basename $WALL)\n"
    done | rofi -dmenu -config $ROFI_CFG
)

if [ ! -z $WALLPAPER ]; then
    hellwal -l -i $WALLPAPER
    swww img $WALLPAPER \
        --transition-type grow \
        --transition-duration 2 \
        --transition-fps 60

    mkdir -p $CONFIG/dunst
    cp $CACHE/hellwal/dunst.toml $CONFIG/dunst/dunstrc
    dunstctl reload
fi
