[urgency_low]
background = "#ffffff"
foreground = "#000000"
frame_color = "#000000"

[urgency_normal]
background = "#ffffff"
foreground = "#f4bf75"
frame_color = "#f4bf75"

[urgency_critical]
background = "#ffffff"
foreground = "#ac4142"
frame_color = "#ac4142"
