#!/usr/bin/env bash

cfg=$HOME/.config
cache=$HOME/.cache/hellwal
walls=$HOME/pictures/walls
img=$(ls $pics | rofi -dmenu)
if [ -z $img ]; then
    exit 1
fi

hellwal -l --image $walls/$img
cp $cache/ColorsHellwal.qml $cfg/quickshell/ColorsHellwal.qml
