#!/usr/bin/env bash

cfg=$HOME/.config
cache=$HOME/.cache/hellwal
walls=$HOME/pictures/wallpapers
img=$(ls $walls | rofi -dmenu)
if [ -z $img ]; then
    exit 1
fi

hellwal -l --image $walls/$img
swww img $walls/$img &

cp $cache/Colors.qml $cfg/quickshell/util
cp $cache/colors.conf $cfg/hypr
